"""empty message

Revision ID: f601fe0e2f5e
Revises: 647138b3928f
Create Date: 2019-10-29 12:51:14.063842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f601fe0e2f5e'
down_revision = '647138b3928f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todolists SET completed = False WHERE completed IS NULL')

    op.alter_column('todolists', 'completed', nullable=False)

    op.execute('ALTER TABLE todos DROP CONSTRAINT todos_list_id_fkey, ADD CONSTRAINT todos_list_id_fkey FOREIGN KEY (list_id) REFERENCES todolists(id) ON DELETE CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolists', 'completed')
    # ### end Alembic commands ###
